-- ============================================================================
-- HR04 Payroll Service - Local Schema (H2)
-- 對應 PO: PayrollRunPO, PayslipPO, PayslipItemPO, SalaryStructurePO, SalaryItemPO
-- ============================================================================

-- 薪資批次
CREATE TABLE IF NOT EXISTS hr04_payroll_runs (
    run_id          VARCHAR(36) PRIMARY KEY,
    name            VARCHAR(100),
    organization_id VARCHAR(36)  NOT NULL,
    payroll_system  VARCHAR(20)  NOT NULL,
    period_start_date DATE       NOT NULL,
    period_end_date   DATE       NOT NULL,
    pay_date        DATE         NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    executor_id     VARCHAR(36),
    approver_id     VARCHAR(36),
    total_employees     INTEGER,
    processed_employees INTEGER,
    failed_employees    INTEGER,
    total_gross_amount  DECIMAL(12,2),
    total_net_amount    DECIMAL(12,2),
    total_deductions    DECIMAL(12,2),
    total_overtime_pay  DECIMAL(12,2),
    executed_at     TIMESTAMP,
    completed_at    TIMESTAMP,
    submitted_by    VARCHAR(36),
    submitted_at    TIMESTAMP,
    approved_at     TIMESTAMP,
    paid_at         TIMESTAMP,
    bank_file_url   VARCHAR(255),
    cancel_reason   TEXT,
    created_by      VARCHAR(36),
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP
);

-- 薪資結構
CREATE TABLE IF NOT EXISTS hr04_salary_structures (
    structure_id    VARCHAR(36) PRIMARY KEY,
    employee_id     VARCHAR(36)  NOT NULL,
    monthly_salary  DECIMAL(10,2),
    daily_rate      DECIMAL(12,2),
    hourly_rate     DECIMAL(10,2),
    payroll_system  VARCHAR(20)  NOT NULL,
    payroll_cycle   VARCHAR(20)  NOT NULL,
    payment_method  VARCHAR(20)  NOT NULL DEFAULT 'BANK_TRANSFER',
    effective_date  DATE         NOT NULL,
    end_date        DATE,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP
);

-- 薪資項目（隸屬薪資結構）
CREATE TABLE IF NOT EXISTS hr04_salary_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id    VARCHAR(36) NOT NULL,
    item_id         VARCHAR(36) NOT NULL,
    item_code       VARCHAR(50) NOT NULL,
    item_name       VARCHAR(100) NOT NULL,
    item_type       VARCHAR(20) NOT NULL,
    amount          DECIMAL(10,2) NOT NULL,
    is_fixed_amount BOOLEAN,
    is_taxable      BOOLEAN,
    is_insurable    BOOLEAN,
    CONSTRAINT fk_salary_item_structure FOREIGN KEY (structure_id) REFERENCES hr04_salary_structures(structure_id)
);

-- 薪資單
CREATE TABLE IF NOT EXISTS hr04_payslips (
    payslip_id      VARCHAR(36) PRIMARY KEY,
    run_id          VARCHAR(36)  NOT NULL,
    employee_id     VARCHAR(36)  NOT NULL,
    employee_code   VARCHAR(20),
    employee_name   VARCHAR(100),
    period_start_date DATE,
    period_end_date   DATE,
    pay_date        DATE,
    base_salary     DECIMAL(10,2),
    gross_wage      DECIMAL(10,2),
    net_wage        DECIMAL(10,2),
    income_tax      DECIMAL(10,2),
    leave_deduction DECIMAL(10,2),
    overtime_pay_total DECIMAL(10,2),
    ot_weekday_hours   DECIMAL(5,2),
    ot_weekday_pay     DECIMAL(10,2),
    ot_restday_hours   DECIMAL(5,2),
    ot_restday_pay     DECIMAL(10,2),
    ot_holiday_hours   DECIMAL(5,2),
    ot_holiday_pay     DECIMAL(10,2),
    ins_labor_fee      DECIMAL(10,2),
    ins_health_fee     DECIMAL(10,2),
    ins_pension_fee    DECIMAL(10,2),
    ins_supplementary_fee DECIMAL(10,2),
    bank_code       VARCHAR(10),
    bank_account_number VARCHAR(30),
    status          VARCHAR(20)  NOT NULL,
    pdf_url         VARCHAR(255),
    email_sent_at   TIMESTAMP,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT fk_payslip_run FOREIGN KEY (run_id) REFERENCES hr04_payroll_runs(run_id)
);

-- 薪資單項目（隸屬薪資單）
CREATE TABLE IF NOT EXISTS hr04_payslip_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payslip_id      VARCHAR(36) NOT NULL,
    item_id         VARCHAR(36) NOT NULL,
    item_code       VARCHAR(50) NOT NULL,
    item_name       VARCHAR(100) NOT NULL,
    display_order   INTEGER,
    item_type       VARCHAR(20) NOT NULL,
    amount          DECIMAL(10,2) NOT NULL,
    source          VARCHAR(20),
    is_taxable      BOOLEAN,
    is_insurable    BOOLEAN,
    CONSTRAINT fk_payslip_item_payslip FOREIGN KEY (payslip_id) REFERENCES hr04_payslips(payslip_id)
);
